image: python:3.7

before_script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py sdist

unit_tests:
  script:
    - python ./test/test_assertion.py test
    - python ./test/test_criterion.py test
    - python ./test/test_diagnosis.py test