image: kvonkoni/osler:v0.1.0

before_script:
  - python setup.py install

unit_tests:
  script:
    - python ./test/test_assertion.py
    - python ./test/test_criterion.py
    - python ./test/test_diagnosis.py
    - python ./test/test_issue.py
    - python ./test/test_graph.py
    - python ./test/test_engine.py