image: python:3.6

before_script:
  - python setup.py install

unit_tests:
  script:
    - python ./test/test_assertion.py test
    - python ./test/test_criterion.py test
    - python ./test/test_diagnosis.py test