image: kvonkoni/osler:v0.2.0

before_script:
  - python3 setup.py install

unit_tests:
  script:
    - python3 ./test/test_assertion.py
    - python3 ./test/test_criterion.py
    - python3 ./test/test_diagnosis.py
    - python3 ./test/test_issue.py
    - python3 ./test/test_graph.py
    - python3 ./test/test_engine.py