image: python:3.7

before_script:
  - python setup.py install
  - python import ete3
  - python ete3.__file__

unit_tests:
  script:
    - python ./test/test_assertion.py test
    - python ./test/test_criterion.py test
    - python ./test/test_diagnosis.py test